### ISSUE TITLE
[BUG]加载插件失败，出现无法读取的字符

### ISSUE THREAD

**Issue by kumiko-desu** [khjxiaogu/MiraiSongPlugin#11]
**描述bug问题**
在mirai启动时，加载插件出现错误，似乎是由于插件的加载中涉及到中文字符的读取，而编码不支持导致读取失败。
**如何重现**
本人能力不足，不清楚重现条件，能给出的信息如下。
问题出现的操作系统信息：

> Linux PureTrifling-VM 4.19.0-6-amd64  SMP Debian 4.19.67-2+deb10u1 (2019-09-20) x86_64 GNU/Linux

系统语言环境：

> LANG=zh_CN.UTF-8
LANGUAGE=
LC_CTYPE="zh_CN.UTF-8"
LC_NUMERIC="zh_CN.UTF-8"
LC_TIME="zh_CN.UTF-8"
LC_COLLATE="zh_CN.UTF-8"
LC_MONETARY="zh_CN.UTF-8"
LC_MESSAGES="zh_CN.UTF-8"
LC_PAPER="zh_CN.UTF-8"
LC_NAME="zh_CN.UTF-8"
LC_ADDRESS="zh_CN.UTF-8"
LC_TELEPHONE="zh_CN.UTF-8"
LC_MEASUREMENT="zh_CN.UTF-8"
LC_IDENTIFICATION="zh_CN.UTF-8"
LC_ALL=

**你希望的修复后结果**
能够正常加载插件
**截屏/报错信息**
![image](https://user-images.githubusercontent.com/53305285/100306076-8163a080-2fdd-11eb-921f-651ae5b593de.png)

**Comment by khjxiaogu** [comment]
似乎是mirai-console的问题，请去[mirai-console](https://github.com/mamoe/mirai-console)反映
