### ISSUE TITLE
[BUG]#QQ 后台有信息却无法发送

### ISSUE THREAD

**Issue by phj233** [khjxiaogu/MiraiSongPlugin#12]
**描述bug问题**
＃QQ 以及 #点歌 QQ音乐 XML无法发送，后台有xml相关信息

**如何重现** 
使用的native 1.9.2  console1.0-M4

**你希望的修复后结果**
能够正常发送

**截屏/报错信息**
![Screenshot_2020-11-30-07-27-55-724_com tencent mobileqq](https://user-images.githubusercontent.com/19668324/100556558-246a3200-32de-11eb-982d-cf79c03fe33b.jpg)
![Screenshot_2020-11-30-07-27-28-322_com microsoft rdc androie](https://user-images.githubusercontent.com/19668324/100556561-27652280-32de-11eb-8cc8-571ce19a6e00.jpg)
![Screenshot_2020-11-30-07-26-59-940_com microsoft rdc androie](https://user-images.githubusercontent.com/19668324/100556563-292ee600-32de-11eb-9996-b985a73b27b1.jpg)

``

**Comment by khjxiaogu** [comment]
可能是新账号被腾讯风控，过几天大概就会好
