### ISSUE TITLE
似乎存在机器人把语音发出来后，无法播放的问题

### ISSUE THREAD

**Issue by STDSuperman** [khjxiaogu/MiraiSongPlugin#23]
如题，这边通过语音指令机器人下载完语音发送到群聊时，发现语音无法播放，时长是有的！

**Comment by khjxiaogu** [comment]
您用的是qq电脑客户端还是手机客户端

**Comment by STDSuperman** [comment]
> 您用的是qq电脑客户端还是手机客户端

都不能播

**Comment by khjxiaogu** [comment]
请提供你的ffmpeg版本

**Comment by STDSuperman** [comment]
FFmpeg SVN-r11143
libavutil   3212544
libavcodec  3354624
libavformat 3408128
FFmpeg version SVN-r11143, Copyright (c) 2000-2007 Fabrice Bellard, et al.
  configuration: --enable-gpl --enable-pp --enable-swscaler --enable-pthreads --enable-liba52 --enable-avisynth --enable-libamr-nb --enable-libamr-wb --enable-libfaac --enable-libfaad --enable-libgsm --enable-libmp3lame --enable-libnut --enable-libtheora --enable-libvorbis --enable-libx264 --enable-libxvid --cpu=i686 --enable-memalign-hack --extra-ldflags=-static

**Comment by khjxiaogu** [comment]
1. 请尝试使用其他方式发送同一音乐，或者使用不同的音乐测试语音功能，检查是否单独音乐的问题。
2. 请尝试收听其他人发送的正常语音，检查是否qq客户端的问题。
3. 请更新到Release最新版本并按照readme重新下载配置ffmpeg。
4. 请提交对应的log和qq聊天界面截图，并提供测试时用的指令。

**Comment by STDSuperman** [comment]
> 1. 请尝试使用其他方式发送同一音乐，或者使用不同的音乐测试语音功能，检查是否单独音乐的问题。
> 2. 请尝试收听其他人发送的正常语音，检查是否qq客户端的问题。
> 3. 请更新到Release最新版本并按照readme重新下载配置ffmpeg。
> 4. 请提交对应的log和qq聊天界面截图，并提供测试时用的指令。

我试试

**Comment by khjxiaogu** [comment]
暂时视为问题已经解决，如有疑问请重开issue

**Comment by STDSuperman** [comment]
> 暂时视为问题已经解决，如有疑问请重开issue

目前尝试下来方案无效QAQ，别人的语音正常，这个的语音就一直无法播放

![)P{U3STPO5UB)6A I%QDM%U](https://user-images.githubusercontent.com/44311619/123498818-b8c62880-d664-11eb-95ef-80581edf0d2b.png)

**Comment by khjxiaogu** [comment]
amr_wb功能情况下，电脑端无法播放。

**Comment by STDSuperman** [comment]
哦哦好吧

**Comment by khjxiaogu** [comment]
如果你需要通用性，可以关闭amr_wb模式。但是这种情况下音频质量会比较差。

**Comment by STDSuperman** [comment]
> 如果你需要通用性，可以关闭amr_wb模式。但是这种情况下音频质量会比较差。

感谢感谢
