### ISSUE TITLE
[BUG]机器人无法发出音乐卡片，显示“无法找到歌曲。”

### ISSUE THREAD

**Issue by Hankxiao0410** [khjxiaogu/MiraiSongPlugin#24]
机器人无法发出音乐卡片，显示“无法找到歌曲。”

![Snipaste_2021-06-24_23-26-20](https://user-images.githubusercontent.com/70145478/123290232-ae603d80-d543-11eb-942c-87e21e17c49d.png)
![QQ截图20210624232333](https://user-images.githubusercontent.com/70145478/123290233-ae603d80-d543-11eb-975d-b3565e430d97.png)

**Comment by Hankxiao0410** [comment]
MiraiSongPlugin为最新版本，Mirai为2.7-M1，麻烦大佬了~
![image](https://user-images.githubusercontent.com/70145478/123290765-1e6ec380-d544-11eb-8308-f925b073bae9.png)

**Comment by khjxiaogu** [comment]
请尝试使用其他音乐指令

**Comment by khjxiaogu** [comment]
实测是没有问题的，可能是如下原因：
1. java版本问题，请提供你的java版本。
2. 网络连接问题，无法连接到音乐平台。
有如下可能的解决方案：
1. 不要使用云服务器(尤其是海外的)
2. 不要使用海外代理
3. 检查主机上能否访问音乐平台主站。

**Comment by Hankxiao0410** [comment]
java版本openJDK-11.0.8因为使用了mirai-native，所以用的32位
不用云服务器我挂哪。。
服务器是国内的，没使用海外代理
主站可以正常连接
![QQ截图2021062507wwwwwww700](https://user-images.githubusercontent.com/70145478/123343309-16cf0f00-d584-11eb-93b7-bb76400f564d.png)
![QQ截图20210625065653](https://user-images.githubusercontent.com/70145478/123342575-90fe9400-d582-11eb-8a24-5bd42f0409e5.png)
（我用不用试试软件？）

**Comment by khjxiaogu** [comment]
可以更新到最新版本，然后调整mirai-console配置里面的logger.yml，把log等级设置为debug，然后把后台报错记录发送一下。

**Comment by Hankxiao0410** [comment]
![logger](https://user-images.githubusercontent.com/70145478/123377424-a7c2dc00-d5be-11eb-835b-48013a8d6415.png)
![debug](https://user-images.githubusercontent.com/70145478/123377411-a2659180-d5be-11eb-9ff0-62a483d4452b.png)

**Comment by khjxiaogu** [comment]
`defaultPriority: DEBUG`

**Comment by Hankxiao0410** [comment]
![debug](https://user-images.githubusercontent.com/70145478/123392451-a51cb280-d5cf-11eb-8bf1-3ae5f848d67f.png)
![QQ截图20210625160913](https://user-images.githubusercontent.com/70145478/123392523-bb2a7300-d5cf-11eb-9cde-392f7ee4f674.png)

**Comment by khjxiaogu** [comment]
请先更新到1.0.2以上

**Comment by Hankxiao0410** [comment]
已更新
![www](https://user-images.githubusercontent.com/70145478/123393202-70f5c180-d5d0-11eb-9f96-112c40f7e8a9.png)

**Comment by Hankxiao0410** [comment]
![SKUG)85TK~ F@ZLIY5`H@W](https://user-images.githubusercontent.com/70145478/123396000-64bf3380-d5d3-11eb-9433-9d431e81c5da.png)
问题已解决，万分感谢！
