### ISSUE TITLE
[BUG]语音功能异常，找不到ffmpeg

### ISSUE THREAD

**Issue by JESVN** [khjxiaogu/MiraiSongPlugin#25]
![Snipaste_2021-06-25_09-40-04](https://user-images.githubusercontent.com/49424543/123355995-63711500-d599-11eb-86e7-580dfb9a488e.png)
![Snipaste_2021-06-25_09-39-50](https://user-images.githubusercontent.com/49424543/123356006-67049c00-d599-11eb-8140-d7834d07c793.png)
是我放的位置不对么？

**Comment by khjxiaogu** [comment]
可以到data/点歌插件/config.yml设置ffmpeg_path为ffmpeg

**Comment by khjxiaogu** [comment]
按照提示应当已经能解决该问题，如果还没解决，请重开issue。
