### ISSUE TITLE
Miraiandroid console2.7 有些歌曲无法找到如何解决[BUG]

### ISSUE THREAD

**Issue by sakuraMY** [khjxiaogu/MiraiSongPlugin#26]
![Screenshot_20210625_201056](https://user-images.githubusercontent.com/67968412/123422940-7ca5b000-d5f1-11eb-84bc-d476465fd87d.jpg)

**Comment by khjxiaogu** [comment]
长时间没回复，暂时视为已经解决，如果尚未解决请重开issue
