### ISSUE TITLE
[BUG]无法正常搜索歌曲

### ISSUE THREAD

**Issue by Stardust-minus** [khjxiaogu/MiraiSongPlugin#30]
全程未出现Error与Warn
**描述bug问题**
点歌时，无法点到正确的歌，通常是名称带有数字的随机歌曲。

**如何重现**
直接点歌即可。

**你希望的修复后结果**
能点到正确的歌

**系统信息**
Windows10 企业版（Azure）
mirai版本：mirai-console-2.7-RC 
MiraiSongPlugin版本：v1.1.2  c8c0d35
查看消息的QQ客户端：电脑/安卓/IOS/其他
**截屏/报错信息**
电脑
![PL30@A@P PJH3EZ4$%}MK4](https://user-images.githubusercontent.com/52093397/130265080-09167330-e5a5-4166-8201-b14031075712.png)

**Comment by khjxiaogu** [comment]
![success](https://user-images.githubusercontent.com/54445543/130312361-8455294f-3f6a-4039-b75c-d834254fcb47.png)
使用2.7-M2测试并没有问题，请问你的操作系统地区和语言？

**Comment by Stardust-minus** [comment]
> ![success](https://user-images.githubusercontent.com/54445543/130312361-8455294f-3f6a-4039-b75c-d834254fcb47.png)
> 使用2.7-RC测试并没有问题，请问你的操作系统地区和语言？

操作系统默认英文，后面自行更改成了中文。
服务器部署在东京，之前在新加坡的时候没有这个BUG，有点神奇

**Comment by khjxiaogu** [comment]
> > ![success](https://user-images.githubusercontent.com/54445543/130312361-8455294f-3f6a-4039-b75c-d834254fcb47.png)
> > 使用2.7-RC测试并没有问题，请问你的操作系统地区和语言？
> 
> 操作系统默认英文，后面自行更改成了中文。
> 服务器部署在东京，之前在新加坡的时候没有这个BUG，有点神奇

网易云在部分地区可能不提供一些歌曲的播放，所以本插件建议在国内使用。

**Comment by khjxiaogu** [comment]
也可以使用连接到国内的代理
