### ISSUE TITLE
建议添加网易云cookie功能已使用vip歌曲的分享

### ISSUE THREAD

**Issue by 502milk** [khjxiaogu/MiraiSongPlugin#31]
cookie需要自己填写

**Comment by khjxiaogu** [comment]
[readme注意事项](https://github.com/khjxiaogu/MiraiSongPlugin#%E6%B3%A8%E6%84%8F)最后一条

> 本插件不会提供账户登录Cookie的功能，也不会设法跳过音乐平台的VIP限制。
