### ISSUE TITLE
[BUG]简述你的问题：我的机器人只能QQ好友点歌，群聊却不行

### ISSUE THREAD

**Issue by imkcp** [khjxiaogu/MiraiSongPlugin#33]
**描述bug问题**

**如何重现**

**你希望的修复后结果**

**系统信息**
mirai版本：
MiraiSongPlugin版本：
查看消息的QQ客户端：电脑/安卓/IOS/其他
**截屏/报错信息**

**Comment by imkcp** [comment]
我的机器人只能好友点歌，群聊却不能点歌

**Comment by khjxiaogu** [comment]
可能是账号被TX认定为风险较高，请测试外链或者其他卡片

**Comment by khjxiaogu** [comment]
不回复视为已经解决，如有疑问请重开issue
