### ISSUE TITLE
[BUG]语音功能无法正常使用？

### ISSUE THREAD

**Issue by sakuraMY** [khjxiaogu/MiraiSongPlugin#36]
电脑显示为一秒无法播放 
手机时长异常且无法播放
amrqualityshift;amrwb 配置均调整过，依旧无法正常播放

**Comment by khjxiaogu** [comment]
时长显示异常是amrwb模式的正常现像，把amrwb设置为false即可解决。
amrwb模式下，电脑无法播放，安卓手机支持播放。
如果amrwb为false仍然无法播放，考虑是qq版本问题。
实测可以正常播放。
