### ISSUE TITLE
[Bug] 使用指令无反应

### ISSUE THREAD

**Issue by whx-prog** [khjxiaogu/MiraiSongPlugin#39]
### 错误现像描述

![(%TE)M@6FMDF3I 9I4)74PR](https://user-images.githubusercontent.com/68294999/145159266-ad4088ac-4a70-459a-abec-9dcbdaf918da.png)
![GSZ%R@PBR1@{QOC@U {%RMU](https://user-images.githubusercontent.com/68294999/145159271-53794075-0d46-411d-ba02-cbc41f4f7d23.png)
   显示加载成功，使用#音乐 test 无回应

### 预计结果

#音乐 test 指令有正常反应

### 重现步骤

将jar放入pligins，使用加载成功后用#音乐 test指令

### 插件版本

2.7-1.1.5

### mirai版本

1.1.0

### 系统信息

windows10

**Comment by khjxiaogu** [comment]
请使用最新版本的mirai
