### ISSUE TITLE
暂未支持核心1.3.0和控制台1.0 m4吗

### ISSUE THREAD

**Issue by Rainforestwind** [khjxiaogu/MiraiSongPlugin#4]

**Comment by khjxiaogu** [comment]
是支持的，因为版本没有大的变化

**Comment by Rainforestwind** [comment]
> 是支持的，因为版本没有大的变化

为什么用console 1.0 m4加载
MiraiSongPlugin最新版会闪退

**Comment by khjxiaogu** [comment]
我的测试环境就是1.0-M4-dev3...

**Comment by Rainforestwind** [comment]
> 我的测试环境就是1.0-M4-dev3 ...

我的是console-1.0-m4.jar环境测试的，不是dev3

**Comment by 4679** [comment]
![Uploading mmexport1600580016733.png…]()
1.0-M4报错

**Comment by khjxiaogu** [comment]
> ![mmexport1600580016733](https://user-images.githubusercontent.com/2030404/93695139-00ec7380-fb46-11ea-8b4f-4a23827579eb.png)
> 
> 1.0-M4报错

已经在0.1.12修复！

**Comment by khjxiaogu** [comment]
> > 我的测试环境就是1.0-M4-dev3 ...
> 
> 我的是console-1.0-m4.jar环境测试的，不是dev3

已经在0.1.12修复！
