### ISSUE TITLE
同一首歌会有不同的歌手唱，机器人发送歌曲名片前希望能选择是哪个歌手唱的

### ISSUE THREAD

**Issue by Remember9** [khjxiaogu/MiraiSongPlugin#41]
### 错误现像描述

同一首歌会有不同的歌手唱，机器人发送歌曲名片前希望能选择是哪个歌手唱的，现在点一首歌曲A，机器人只会发过来一个歌手的版本，但那个版本可能并不是自己想听的

### 预计结果

点歌后有机器人先返回一个歌曲及其演唱歌手的列表，用户向机器人继续发送序号，根据序号选择要听哪个歌手唱的版本。这个功能可以让用户选择是否开启，不开启则维持插件现状。

### 重现步骤

冒昧的提了个需求，作者大大觉得这个功能没有必要请忽略哈，不要生气

### 插件版本

最新

### mirai版本

最新

### 系统信息

最新

**Comment by khjxiaogu** [comment]
你可以直接在搜索关键词里写上歌手

**Comment by Remember9** [comment]
好的谢谢，我知道了，我之前加上歌手名但没有返回那个歌手唱的版本是因为听那首歌需要会员，会员才能听的歌插件是不能返回的吧
