### ISSUE TITLE
希望能添加方便群主和管理员使用的单群开关

### ISSUE THREAD

**Issue by TheStarN** [khjxiaogu/MiraiSongPlugin#42]
### 错误现像描述

现在点歌功能不能方便的由群主和管理员在单个群聊中开启和关闭。希望能添加相应功能。

### 预计结果

当机器人在群聊中收到由群主或管理员发送的“#开启点歌”指令时，添加权限配置“+*@<群号>”
当机器人在群聊中收到由群主或管理员发送的“#关闭点歌”指令时，添加权限配置“-*@<群号>”
“#开启点歌”和“#关闭点歌”指令应当可以自定义。

### 重现步骤

无

### 插件版本

最新

### mirai版本

最新

### 系统信息

Windows Server 2019

**Comment by hundun000** [comment]
我有试过[把Permissions系统用于Command以外的权限控制](https://mirai.mamoe.net/topic/535)。如果应用于本issue，即是把Permissions系统用于本插件的EventListener的工作开关控制。最终效果就不是管理员用“#开启点歌/#关闭点歌”进行开关，而是拥有mirai-console的人通过/perm来开关。如同链接帖子所述，可以复用Permissions系统，省去新增配置文件和检查权限逻辑等工作量。

开关后的config/Console/PermissionService.yml内容示例：

```
grantedPermissionMap:
    '点歌插件.cos:INSTANCE': # 特殊权限，表示本插件(点歌插件)的开关
        - m111111.222222 # bot账号222222在群1111111启用本插件
```

 如果 @khjxiaogu 认为这个方案可以接受，我可以尝试提供PR。

**Comment by khjxiaogu** [comment]
> 我有试过[把Permissions系统用于Command以外的权限控制](https://mirai.mamoe.net/topic/535)。如果应用于本issue，即是把Permissions系统用于本插件的EventListener的工作开关控制。最终效果就不是管理员用“#开启点歌/#关闭点歌”进行开关，而是拥有mirai-console的/perm权限的人来开关。如同链接帖子所述，可以复用Permissions系统，省去新增配置文件和检查权限逻辑等工作量。
> 
> 开关后的config/Console/PermissionService.yml内容示例：
> 
> ```
> grantedPermissionMap:
>     '点歌插件.cos:INSTANCE': # 特殊权限，表示本插件(点歌插件)的开关
>         - m111111.222222 # bot账号222222在群1111111启用本插件
> ```
> 
> 如果 @khjxiaogu 认为这个方案可以接受，我可以尝试提供PR。

值得尝试，但是我并不确定官方权限系统的稳定性，如果这个稳定性、安全性和易用性都可以接受，也未尝不可。
（毕竟之前出现过一些比较大的安全漏洞

**Comment by hundun000** [comment]
我又仔细看了下文档，看起来本插件现有权限系统：
> +*@1111111 #表示允许群1111111里的所有人使用

等效于我打算加的：
> 点歌插件.cos:INSTANCE: m111111.* #表示(任意bot账号)在群1111111启用本插件

也就是现有权限系统已经能通过改配置文件实现issue需求了，缺的是用指令动态编辑？如果是这样的话，我的方案优势也不会很大了，那就算了吧。
