### ISSUE TITLE
除了酷狗，其他源均无法检索到歌曲[Bug] 

### ISSUE THREAD

**Issue by Speechless22** [khjxiaogu/MiraiSongPlugin#48]
### 错误现像描述

催更

### 预计结果

催更

### 重现步骤

![20220604_053614788_iOS](https://user-images.githubusercontent.com/61347609/171986513-52850760-7f77-4fd4-b394-bd847c6416f7.jpg)

### 错误报告

[mcl.log](https://github.com/khjxiaogu/MiraiSongPlugin/files/8837111/mcl.log)

### 插件版本

2.7-1.7.7

### mirai版本

2.11.1

### 系统信息

Ubuntu_Aarch64

### 配置文件
[config.yml.txt](https://github.com/khjxiaogu/MiraiSongPlugin/files/8837116/config.yml.txt)

**Comment by khjxiaogu** [comment]
Please provide more details.

**Comment by khjxiaogu** [comment]
未能复现问题，请参照主页的README自行进行问题排查或者提供详细log和报告，若在今天内不提供视为已经解决

**Comment by Speechless22** [comment]
> 请提供更多细节。

来了

**Comment by khjxiaogu** [comment]
> > 请提供更多细节。
> 
> 来了

根据测试，并没有这样的情况，对照README的注意事项排查。

**Comment by khjxiaogu** [comment]
![V`VG%(Z1RO2F1~O9H(22F0E](https://user-images.githubusercontent.com/54445543/171992501-ff59212a-81f7-4833-b5dd-d86622a5b125.png)
