### ISSUE TITLE
[BUG] 是否支持 mirai-console 1.0-M3 ？

### ISSUE THREAD

**Issue by nlpguyz** [khjxiaogu/MiraiSongPlugin#5]
**描述bug问题**
在 mirai-console-1.0-M3 版本下运行不出点歌

**如何重现**
登录后，群中输入”点歌 歌名“没有反应

**你希望的修复后结果**
可以点歌

**截屏/报错信息**
n/a

**Comment by nlpguyz** [comment]
M4

**Comment by khjxiaogu** [comment]
点歌命令是有3个参数的，否则是不会工作的，请仔细阅读readme!
