### ISSUE TITLE
[Bug] 一些源似乎无法正常工作

### ISSUE THREAD

**Issue by Initial-heart-1** [khjxiaogu/MiraiSongPlugin#50]
### 错误现像描述

命令：`#QQ 最伟大的作品`（从排行榜找来验证的确有这首歌） `#千千 国歌`
返回：`无法找到歌曲。`
任何关键词均有此故障
酷狗和网易工作正常

### 预计结果

正常运行

### 重现步骤

并不清楚如何重现，故障是突然发生的（千千不确定，因为没有人使用过）。
最近一次的更改是使用 mcl 将 mirai（core console）升级至 2.12.0。

### 错误报告

QQ：https://paste.ubuntu.com/p/mJ742fqsWj/
千千：https://paste.ubuntu.com/p/s3f7qFQSWm/
> 为什么分成了两个？因为后面我看了文档才测了一下千千

### 插件版本

1.1.7

### mirai版本

2.12.0

### 系统信息

Windows 10 专业版 21H2

**Comment by Initial-heart-1** [comment]
另外，不清楚为何日志等级为 Debug。我设定的日志等级为 Debug 所以找到了相关日志。

**Comment by khjxiaogu** [comment]
应该是QQ音乐关闭了对应的API接口
