### ISSUE TITLE
[Bug] Mirai 2.12.1，点歌插件v1.1.7，可加载但无法使用

### ISSUE THREAD

**Issue by DeadBoy2537** [khjxiaogu/MiraiSongPlugin#51]
### 错误现像描述

成功加载插件但无法使用，/status打印结果显示disabled
![IMG_20220821_190711](https://user-images.githubusercontent.com/87133530/185788817-6686143d-e348-4c0f-9350-919c8a4ce6d4.jpg)
![IMG_20220821_190011](https://user-images.githubusercontent.com/87133530/185788822-eadbbe1a-b1ba-4fe0-825e-4586837310dc.jpg)

### 预计结果

插件能够正常使用

### 重现步骤

Mirai版本2.12.1

### 插件版本

1.1.7

### mirai版本

2.12.1

### 系统信息

CentOS 8

**Comment by DeadBoy2537** [comment]
/status 后打印出来的信息
![IMG_20220821_193330](https://user-images.githubusercontent.com/87133530/185788990-c2db6212-043f-4f0f-9d37-14b8890c5e4a.jpg)

**Comment by khjxiaogu** [comment]
我使用2.11.0和2.12.2测试均不能重现，建议您更新成对应版本

**Comment by DeadBoy2537** [comment]
经过排查最终发现是onebot插件版与点歌插件冲突

**Comment by DeadBoy2537** [comment]
> 我使用2.11.0和2.12.2测试均不能重现，建议您更新成对应版本

经过排查最终发现是onebot插件版与点歌插件冲突
