### ISSUE TITLE
佬，权限怎么弄啊。。。。没理解明白

### ISSUE THREAD

**Issue by weizid** [khjxiaogu/MiraiSongPlugin#53]
### 建议功能描述

想弄成机器人是管理或者群主的群里所有人允许使用。不允许qq好友使用，不允许群私聊使用，应该怎么填写啊。。。

**Comment by khjxiaogu** [comment]
可以先-*禁止所有人使用
> 机器人是管理或者群主的群里所有人允许使用
请自行在readme中寻找答案。
