### ISSUE TITLE
“机器人是管理或者群主的群里，允许所有人使用。不允许QQ好友使用，不允许群私聊使用”，是这样子填吗

### ISSUE THREAD

**Issue by weizid** [khjxiaogu/MiraiSongPlugin#54]
![QQ截图20221011203851](https://user-images.githubusercontent.com/37445278/195093575-38a5d4e6-30b2-49ca-b213-2d671d0f1bae.png)
是一行一个吗，我这样填好像没被应用。。。
求教。。。

**Comment by khjxiaogu** [comment]
请再次阅读README并参考提供的范例，并且不要再次创建issue了，请在本issue下添加回复。

**Comment by weizid** [comment]
> 

佬，求教下，我太笨了。。。

> 请再次阅读README并参考提供的范例，并且不要再次创建issue了，请在本issue下添加回复。

**Comment by khjxiaogu** [comment]
请再次阅读README并参考提供的范例。
