### ISSUE TITLE
[建议]大佬，请问有办法提升外观为AMR音乐插件输出的音频质量吗，或者解除amrqualityshift中音频文件1m大小的限制

### ISSUE THREAD

**Issue by GuoDong114514** [khjxiaogu/MiraiSongPlugin#56]
### 建议功能描述

[建议]大佬，请问有办法提升外观为AMR音乐插件输出的音频质量吗，或者解除amrqualityshift中音频文件1m大小的限制

### 为什么要添加这个功能？

想要提升体验

**Comment by khjxiaogu** [comment]
这个限制是由于QQ自身限制语音最大大小为1M导致，插件只是保证了能够正常发送。
**请给腾讯提议要求提升语音质量**
