### ISSUE TITLE
语音功能不能正常使用[Bug] 

### ISSUE THREAD

**Issue by 1233Ao** [khjxiaogu/MiraiSongPlugin#58]
### 错误现像描述

语音只有1秒，可以播放但是没有声音

### 预计结果

能用

### 重现步骤

加上插件
把ffmpeg.exe放到bot目录
执行指令#语音 歌名

### 错误报告

https://paste.fastmirror.net/?b02ddfd51c4238a2#E5kFT3zW6ZQPpmqw8GstJQH2yp5ynKkeMfwgy6C3T86U

### 插件版本

MiraiSongPlugin-2.7-1.2.1

### mirai版本

 2.14.0,

### 系统信息

win11

**Comment by khjxiaogu** [comment]
[关于明明首页README就有但是就是没人看这件事](https://github.com/khjxiaogu/MiraiSongPlugin#%E9%85%8D%E7%BD%AE%E9%A1%B9)
