### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by XC084** [khjxiaogu/MiraiSongPlugin#59]
### 错误现像描述

网易的api好像挂了
搜索网易的歌都是搜不到歌曲
(浅测了一下应该是只有QQ音乐活着
因为是半夜在床上突然想用一下发现用不了所以没看后台
（是旧bot刚打完复活赛（（

### 预计结果

能用bot搜索其他平台歌

### 重现步骤

插件一年多没更挂一两个api很正常吧（（

### 插件版本

最新版-自动解析

### mirai版本

2.16

### 系统信息

win11

### 提交前我已确定：

- [X] 我已阅读README，没有发现对应内容。
- [X] 我已在issue内搜索，没有发现已有的issue。

**Comment by khjxiaogu** [comment]
确实挂了，暂时没办法修，wy给网上所有API都律师函警告了😅

**Comment by khjxiaogu** [comment]
1.2.2修复网易链接，其他平台没人用暂不修复
