### ISSUE TITLE
[BUG]网易、酷狗卡片发不出来

### ISSUE THREAD

**Issue by Dracl** [khjxiaogu/MiraiSongPlugin#6]
#网易 #酷狗 指令有效并且后台看到有搜索信息，但是发不出来，怀疑是tx改了卡片的规范。
#QQ 正常。
![image](https://user-images.githubusercontent.com/44107571/94349585-6249a080-0078-11eb-9fa2-ce51220b7885.png)

群里大佬分析：
![image](https://user-images.githubusercontent.com/44107571/94349620-cf5d3600-0078-11eb-833b-9b2b90b5ae4e.png)
![image](https://user-images.githubusercontent.com/44107571/94349624-de43e880-0078-11eb-869a-370b2a9fe79b.png)

**Comment by khjxiaogu** [comment]
已收到，将尽快恢复，XML卡片不受影响。
